import "./globals.css";
import type { Metadata } from "next";
import { Montserrat, Dancing_Script } from "next/font/google";

const mont = Montserrat({ subsets: ["latin"], variable: "--font-mont" });

const dancing = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${mont.variable} ${dancing.variable} tw-font-sans`}>
        {children}
      </body>
    </html>
  );
}
