import "./globals.css";
import type { Metadata } from "next";
import { Poppins, Dancing_Script } from "next/font/google";

const mont = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-mont",
});

const dancing = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${mont.variable} ${dancing.variable} tw-font-sans tw-text-zinc-800`}
      >
        {children}
      </body>
    </html>
  );
}
